# Generated by Django 5.0.14 on 2025-06-13 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_equipo_capitan_equipo_carrera_equipo_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FixtureGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('mixto', 'Mixto')], max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('total_jornadas', models.IntegerField()),
                ('total_partidos', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.disciplina')),
            ],
            options={
                'verbose_name': 'Fixture Generado',
                'verbose_name_plural': 'Fixtures Generados',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('mixto', 'Mixto')], max_length=20)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('lugar', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('en_vivo', 'En Vivo'), ('finalizado', 'Finalizado')], default='programado', max_length=20)),
                ('goles_equipo_a', models.IntegerField(blank=True, default=0, null=True)),
                ('goles_equipo_b', models.IntegerField(blank=True, default=0, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('jornada', models.IntegerField(blank=True, help_text='Número de jornada del fixture', null=True)),
                ('es_fixture', models.BooleanField(default=False, help_text='Indica si fue generado automáticamente')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_creados', to=settings.AUTH_USER_MODEL)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.disciplina')),
                ('equipo_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_como_equipo_a', to='usuarios.equipo')),
                ('equipo_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_como_equipo_b', to='usuarios.equipo')),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
                'ordering': ['fecha', 'hora'],
            },
        ),
        migrations.AddConstraint(
            model_name='partido',
            constraint=models.CheckConstraint(check=models.Q(('equipo_a', models.F('equipo_b')), _negated=True), name='no_mismo_equipo'),
        ),
    ]
