# Generated by Django 5.0.14 on 2025-06-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidos', '0001_initial'),
        ('usuarios', '0002_equipo_capitan_equipo_carrera_equipo_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixturegenerado',
            name='completado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fixturegenerado',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fixturegenerado',
            name='jornadas_generadas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fixturegenerado',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fixturegenerado',
            name='total_partidos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='fixturegenerado',
            unique_together={('disciplina', 'categoria')},
        ),
    ]
