# Generated by Django 5.0.14 on 2025-06-13 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidos', '0002_fixturegenerado_completado_and_more'),
        ('usuarios', '0002_equipo_capitan_equipo_carrera_equipo_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoPartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('gol', 'Gol'), ('punto', 'Punto'), ('tarjeta_amarilla', 'Tarjeta Amarilla'), ('tarjeta_roja', 'Tarjeta Roja'), ('cambio', 'Cambio de Jugador'), ('inicio_tiempo', 'Inicio de Tiempo'), ('fin_tiempo', 'Fin de Tiempo'), ('otro', 'Otro')], default='gol', max_length=20)),
                ('minuto', models.IntegerField(blank=True, help_text='Minuto en que ocurrió el evento', null=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción adicional del evento')),
                ('valor', models.IntegerField(default=1, help_text='Valor del evento (ej: 1 para gol, 2 para punto de 2, etc.)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True, help_text="Permite 'eliminar' un evento sin borrarlo")),
                ('equipo', models.ForeignKey(help_text='Equipo al que se le asigna el evento', on_delete=django.db.models.deletion.CASCADE, to='usuarios.equipo')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='partidos.partido')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de Partido',
                'verbose_name_plural': 'Eventos de Partido',
                'ordering': ['timestamp'],
            },
        ),
    ]
