# Generated by Django 5.0.14 on 2025-06-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_equipo_capitan_equipo_carrera_equipo_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='puntos_olimpiada',
            field=models.IntegerField(default=0, help_text='Puntos acumulados en la olimpiada'),
        ),
    ]
