# Generated by Django 5.0.14 on 2025-05-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_carrera_perfil_estado_verificacion_perfil_rol_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Juez',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('especialidad', models.CharField(max_length=255)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Juez',
                'verbose_name_plural': 'Jueces',
                'ordering': ['nombre_completo'],
            },
        ),
    ]
